-- ============================
-- CREACIÓN Y OPTIMIZACIÓN DB SYNKTIME
-- ============================
    CREATE DATABASE IF NOT EXISTS synktime;
    USE synktime;

-- ============================
-- CREACIÓN DE TABLAS
-- ============================

CREATE TABLE EMPRESA (
    ID_EMPRESA      INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE          VARCHAR(100) NOT NULL UNIQUE,
    RUC             VARCHAR(20),
    DIRECCION       VARCHAR(200),
    ESTADO          CHAR(1) DEFAULT 'A'
);

CREATE TABLE USUARIO (
    ID_USUARIO      INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME        VARCHAR(50) NOT NULL UNIQUE,
    CONTRASENA      VARCHAR(255) NOT NULL,
    NOMBRE_COMPLETO VARCHAR(100) NOT NULL,
    EMAIL           VARCHAR(100) NOT NULL,
    ROL             VARCHAR(30) NOT NULL,
    ID_EMPRESA      INT NOT NULL,
    ESTADO          CHAR(1) DEFAULT 'A',
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA)
);

CREATE TABLE SEDE (
    ID_SEDE         INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE          VARCHAR(100) NOT NULL,
    DIRECCION       VARCHAR(200),
    ID_EMPRESA      INT NOT NULL,
    ESTADO          CHAR(1) DEFAULT 'A',
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA)
);

CREATE TABLE ESTABLECIMIENTO (
    ID_ESTABLECIMIENTO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE          VARCHAR(100) NOT NULL,
    DIRECCION       VARCHAR(200),
    ID_SEDE         INT NOT NULL,
    ESTADO          CHAR(1) DEFAULT 'A',
    FOREIGN KEY (ID_SEDE) REFERENCES SEDE(ID_SEDE)
);

CREATE TABLE EMPLEADO (
    ID_EMPLEADO     INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE          VARCHAR(100) NOT NULL,
    APELLIDO        VARCHAR(100) NOT NULL,
    DNI             VARCHAR(20) NOT NULL UNIQUE,
    CORREO          VARCHAR(100),
    TELEFONO        VARCHAR(20),
    ID_ESTABLECIMIENTO INT NOT NULL,
    FECHA_INGRESO   DATE,
    ESTADO          CHAR(1) DEFAULT 'A',
    ACTIVO          CHAR(1) DEFAULT 'N',
    FOREIGN KEY (ID_ESTABLECIMIENTO) REFERENCES ESTABLECIMIENTO(ID_ESTABLECIMIENTO)
);

CREATE TABLE HORARIO (
    ID_HORARIO      INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE          VARCHAR(50) NOT NULL,
    HORA_ENTRADA    CHAR(5) NOT NULL,
    HORA_SALIDA     CHAR(5) NOT NULL,
    TOLERANCIA      INT DEFAULT 0
);

CREATE TABLE EMPLEADO_HORARIO (
    ID_EMPLEADO     INT NOT NULL,
    ID_HORARIO      INT NOT NULL,
    FECHA_DESDE     DATE NOT NULL,
    FECHA_HASTA     DATE,
    PRIMARY KEY (ID_EMPLEADO, ID_HORARIO, FECHA_DESDE),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO),
    FOREIGN KEY (ID_HORARIO) REFERENCES HORARIO(ID_HORARIO)
);

CREATE TABLE ASISTENCIA (
    ID_ASISTENCIA   INT AUTO_INCREMENT PRIMARY KEY,
    ID_EMPLEADO     INT NOT NULL,
    FECHA           DATE NOT NULL,
    TIPO            VARCHAR(10) NOT NULL, -- 'ENTRADA' o 'SALIDA'
    HORA            CHAR(5) NOT NULL,
    TARDANZA        CHAR(1) DEFAULT 'N',
    OBSERVACION     VARCHAR(200),
    REGISTRO_MANUAL CHAR(1) DEFAULT 'N',
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
);

CREATE TABLE JUSTIFICACION (
    ID_JUSTIFICACION INT AUTO_INCREMENT PRIMARY KEY,
    ID_EMPLEADO      INT NOT NULL,
    FECHA            DATE NOT NULL,
    MOTIVO           VARCHAR(200),
    APROBADO         CHAR(1) DEFAULT 'N',
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
);

CREATE TABLE LOG (
    ID_LOG           INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO       INT,
    FECHA_HORA       DATETIME DEFAULT CURRENT_TIMESTAMP,
    ACCION           VARCHAR(100),
    DETALLE          VARCHAR(500),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

-- ============================
-- OPTIMIZACIÓN: ÍNDICES
-- ============================

CREATE INDEX IDX_EMPRESA_ESTADO ON EMPRESA(ESTADO);
CREATE INDEX IDX_USUARIO_EMPRESA ON USUARIO(ID_EMPRESA);
CREATE INDEX IDX_USUARIO_ESTADO ON USUARIO(ESTADO);
CREATE INDEX IDX_SEDE_EMPRESA ON SEDE(ID_EMPRESA);
CREATE INDEX IDX_ESTABLECIMIENTO_SEDE ON ESTABLECIMIENTO(ID_SEDE);
CREATE INDEX IDX_EMPLEADO_ESTABLECIMIENTO ON EMPLEADO(ID_ESTABLECIMIENTO);
CREATE INDEX IDX_EMPLEADO_ESTADO ON EMPLEADO(ESTADO);
CREATE INDEX IDX_EMPLEADO_ACTIVO ON EMPLEADO(ACTIVO);
CREATE INDEX IDX_ASISTENCIA_EMPLEADO ON ASISTENCIA(ID_EMPLEADO);
CREATE INDEX IDX_ASISTENCIA_FECHA ON ASISTENCIA(FECHA);
CREATE INDEX IDX_JUSTIFICACION_EMPLEADO ON JUSTIFICACION(ID_EMPLEADO);
CREATE INDEX IDX_LOG_USUARIO ON LOG(ID_USUARIO);

-- ============================
-- VISTAS ÚTILES
-- ============================

CREATE OR REPLACE VIEW VW_EMPLEADOS_ACTIVOS AS
SELECT ID_EMPLEADO, NOMBRE, APELLIDO, ACTIVO
FROM EMPLEADO
WHERE ACTIVO = 'S';
